### ISSUE TITLE
Why the optimizer is error

### ISSUE THREAD

**Issue by lizixiaoboluo** [JittorRepos/JDiffusion#2]

**Comment by lizixiaoboluo** [comment]
Traceback (most recent call last):
  File "/home/JDiffusion/examples/dreambooth/train.py", line 703, in <module>
    main(args)
  File "/home/JDiffusion/examples/dreambooth/train.py", line 526, in main
    optimizer = AdamW(
  File "/home/.conda/envs/jdiffusion/lib/python3.9/site-packages/jittor/optim.py", line 439, in __init__
    values.append(jt.zeros(p.shape, p.dtype).stop_grad())
  File "/home/.conda/envs/jdiffusion/lib/python3.9/site-packages/jittor/__init__.py", line 500, in zeros
    return unary(0, dtype).broadcast(shape)
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.broadcast)).

Types of your inputs are:
 self	= Var,
 args	= (Size, ),

The function declarations are:
 VarHolder* broadcast_to(VarHolder* x,  NanoVector shape,  NanoVector dims=NanoVector())
 VarHolder* broadcast_to_(VarHolder* x, VarHolder* y,  NanoVector dims=NanoVector()

**Comment by wangyePHD** [comment]
same issue

**Comment by yeyu-cpu** [comment]
have you solved this issue/

**Comment by yeyu-cpu** [comment]
have you solved this issue？
