### ISSUE TITLE
Problem with import torch.cuda

### ISSUE THREAD

**Issue by jiangzizi** [JittorRepos/JDiffusion#3]
在运行 run_all.py 时遇到问题

Traceback (most recent call last):
  File "/root/JDiffusion/examples/dreambooth/run_all.py", line 3, in <module>
    from JDiffusion.pipelines import StableDiffusionPipeline
  File "/root/JDiffusion/python/JDiffusion/__init__.py", line 2, in <module>
    from .models import (
  File "/root/JDiffusion/python/JDiffusion/models/__init__.py", line 1, in <module>
    from .autoencoder_kl_jittor import AutoencoderKL
  File "/root/JDiffusion/python/JDiffusion/models/autoencoder_kl_jittor.py", line 19, in <module>
    from diffusers.loaders import FromOriginalVAEMixin
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/root/anaconda3/envs/jdiffusion/lib/python3.9/site-packages/diffusers/utils/import_utils.py", line 692, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/anaconda3/envs/jdiffusion/lib/python3.9/site-packages/diffusers/utils/import_utils.py", line 704, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.single_file because of the following error (look up to see its traceback):
No module named 'torch.cuda.amp'; 'torch.cuda' is not a package

已经确认安装了 torch

**Comment by LDYang694** [comment]
请按照Readme里面的内容安装依赖
